### PR TITLE
Update portugal.m3u

### PR DESCRIPTION
**Pull request by rdscorreia74**
I am an old github user but I am very new to using github and to the trying to help with commits/pull requests. Please accept my apologies if I am failing netiquette-wise. It's just that I don't actually know how this works.

I've forked your project just for the purpose of trying to help with typos or adding more sources that I may find later.
Sorry for having created the PR before making all the commits. As said, new to this "world"...

On this commit I edited some names that had weird characters on them.
The word "radio" is spelled "rádio" in Portuguese but I left all "radio" words unchanged, I just didn't find the need to make it uniform across the whole playlist.

### CODE REVIEW

**Comment by junguler** [comment]
hello, i appreciate the PR but it's not nearly substantial enough to warrant merging, please don't waste your time and just submit an issue that i can fix with the next push

if you have something that would greatly improve this repo in a meaningful way i would gladly accept it

**Comment by junguler** [comment]
hello again, i don't have any issues with how you made this PR, i'm not very efficient with my git pushes either

it's just i haven't accepted any PR to this repo yet as most of them either didn't explain what they were trying to do or like in your case changed too little

**Comment by rdscorreia74** [comment]
> or like in your case changed too little

Cool stuff :+1: 
Actually, I think I changed it quite a bit, because I added the radio="true" tag on every source of the Portuguese m3u. It is needed for some m3u players to be able to distinguish audio-only from video+audio streams. For instance, it's perfect for Kodi.
But to be honest, it's quite ok that you don't pull it. ;-)
I think I'll create a whole new project of mine based on your Portuguese and Hardrock m3u's, but of course only if that's fine with you. ;-)

**Comment by junguler** [comment]
yes, that's a perfect idea, please send me a link when it's done and i'll make sure to star your repo

**Comment by rdscorreia74** [comment]
Sure. Will do.
Thanks a bunch.
Cheers

**Comment by rdscorreia74** [comment]
Hi @junguler 
Here it is. :-)
https://github.com/rdscorreia74/m3u_radios
Thank a bunch.
Cheers

**Comment by junguler** [comment]
amazing

**Pull request closed without merging**
